name: Deploy static site to Azure Static Web Apps

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch
  workflow_dispatch:  # allows manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get OIDC token for Azure
      id: idtoken
      uses: actions/github-script@v6
      with:
        script: return await core.getIDToken()

    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "/"                     # Your static HTML files are in the root
        api_location: ""                      # No backend API
        output_location: "/"                 # No build output folder
        azure_static_web_apps_api_token: ""  # Not needed when using OIDC
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_id_token: ${{ steps.idtoken.outputs.result }}
        env: "Production"                     # Optional environment name
